"""birthday_contacts

Revision ID: 46498f9d326d
Revises: f9dd2cde8c66
Create Date: 2023-10-07 00:27:21.136491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46498f9d326d'
down_revision: Union[str, None] = 'f9dd2cde8c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
